### ISSUE TITLE
Add `$`(ResultFailure e) = e.msg

### ISSUE THREAD

**Issue by Bulat-Ziganshin** [status-im/questionable#15]
When we have `x : ?!T` and use `x.expect(...)`, we don't see x.e.msg in the raised exception because [this code](https://github.com/status-im/nim-stew/blob/dad28a269fa0838635a0310f9d1456680f7bbff5/stew/results.nim#L344) tries to use $(x.e) which is undefined for ResultFailure

See example in https://github.com/status-im/nim-codex/pull/160#issuecomment-1201753390

**Comment by markspanbroek** [comment]
Yes, not having a $ for errors is annoying. I ran into this [a while ago](https://github.com/status-im/questionable/pull/9#issuecomment-1010837011) myself.

I tried adding the following to results.nim:

```nim
proc `$`*(error: ref CatchableError): string =
  error.msg
```

But this somehow breaks an [unrelated test for `catch`](https://github.com/status-im/questionable/blob/955597a4fdadb239bcbb3581e14f59bb29529758/testmodules/result/test.nim#L286).

Root cause seems to be [this issue in `nim-result`](https://github.com/arnetheduck/nim-result/issues/21).
